name: watch-watcher

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours at midnight (UTC)

jobs:
  price_tracking:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium fake-useragent webdriver-manager

      # Configure Proxychains for DNS resolution
      - name: Configure proxychains
        run: |
          echo "proxy_dns" | sudo tee -a /etc/proxychains.conf
          echo "strict_chain" | sudo tee -a /etc/proxychains.conf

      # Run the script with Proxy
      - name: Run Price Tracker with Proxy
        run: |
          proxychains python main.py

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add myntra.csv
          git commit -m "Update price data"
          git push


