name: watch-watcher

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours at midnight (UTC)

jobs:
  price_tracking:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium fake-useragent webdriver-manager

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -f install

      # Install ChromeDriver (latest version)
      - name: Install ChromeDriver
        run: |
          # Get the latest version of ChromeDriver
          LATEST=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Verify Google Chrome Installation
      - name: Verify Google Chrome Installation
        run: google-chrome-stable --version

      # Verify ChromeDriver Installation
      - name: Verify ChromeDriver Installation
        run: chromedriver --version

      # Run the script
      - name: Run Price Tracker
        run: python main.py

      # Commit and Push Changes if modified
      - name: Commit and Push Changes if modified
        run: |
          git diff --quiet myntra.csv || git commit -am "Update price data" && git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
